package com.xst.bean;
// Generated 2016-2-8 20:31:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * V9AdminRole generated by hbm2java
 */
@Entity
@Table(name = "v9_admin_role", catalog = "db_xst")
public class V9AdminRole implements java.io.Serializable {

	private Byte roleid;
	private String rolename;
	private String description;
	private short listorder;
	private boolean disabled;
	private Set<V9Admin> v9Admins = new HashSet<>();
	
	public V9AdminRole() {
	}

	public V9AdminRole(String rolename, String description, short listorder, boolean disabled, Set<V9Admin> v9Admins) {
		this.rolename = rolename;
		this.description = description;
		this.listorder = listorder;
		this.disabled = disabled;
		this.v9Admins = v9Admins;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "v9AdminRole")
	public Set<V9Admin> getV9Admins() {
		return v9Admins;
	}

	public void setV9Admins(Set<V9Admin> v9Admins) {
		this.v9Admins = v9Admins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roleid", unique = true, nullable = false)
	public Byte getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Byte roleid) {
		this.roleid = roleid;
	}

	@Column(name = "rolename", nullable = false, length = 50)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "listorder", nullable = false)
	public short getListorder() {
		return this.listorder;
	}

	public void setListorder(short listorder) {
		this.listorder = listorder;
	}

	@Column(name = "disabled", nullable = false)
	public boolean isDisabled() {
		return this.disabled;
	}

	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

}
