package com.xst.bean;
// Generated 2016-2-8 20:31:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * V9Admin generated by hbm2java
 */
@Entity
@Table(name = "v9_admin", catalog = "db_xst")
public class V9Admin implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String password;
	private V9AdminRole v9AdminRole;
	private String encrypt;
	private String lastloginip;
	private Integer lastlogintime;
	private String email;
	private String realname;
	private String card;
	private String lang;

	public V9Admin() {
	}

	public V9Admin(String realname, String card, String lang) {
		this.realname = realname;
		this.card = card;
		this.lang = lang;
	}

	public V9Admin(String username, String password, Short roleid, String encrypt, String lastloginip,
			Integer lastlogintime, String email, String realname, String card, String lang, V9AdminRole v9AdminRole) {
		this.username = username;
		this.password = password;
		this.encrypt = encrypt;
		this.lastloginip = lastloginip;
		this.lastlogintime = lastlogintime;
		this.email = email;
		this.realname = realname;
		this.card = card;
		this.lang = lang;
		this.v9AdminRole = v9AdminRole;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid", nullable = true)
	public V9AdminRole getV9AdminRole() {
		return v9AdminRole;
	}

	public void setV9AdminRole(V9AdminRole v9AdminRole) {
		this.v9AdminRole = v9AdminRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userid", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "username", length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "encrypt", length = 6)
	public String getEncrypt() {
		return this.encrypt;
	}

	public void setEncrypt(String encrypt) {
		this.encrypt = encrypt;
	}

	@Column(name = "lastloginip", length = 15)
	public String getLastloginip() {
		return this.lastloginip;
	}

	public void setLastloginip(String lastloginip) {
		this.lastloginip = lastloginip;
	}

	@Column(name = "lastlogintime")
	public Integer getLastlogintime() {
		return this.lastlogintime;
	}

	public void setLastlogintime(Integer lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "realname", nullable = false, length = 50)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "card", nullable = false)
	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	@Column(name = "lang", nullable = false, length = 6)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

}
