package com.xst.bean;
// Generated 2016-2-20 22:32:32 by Hibernate Tools 3.2.2.GA

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Set;

/**
 * V9NewsData generated by hbm2java
 */
@Entity
@Table(name = "v9_news_data"
		, schema = "db_xst")
public class V9NewsData  implements java.io.Serializable{

	private Integer id;
	private String content;
	private short readpoint;
	private String groupidsView;
	private boolean paginationtype;
	private int maxcharperpage;
	private String template;
	private boolean paytype;
	private String relation;
	private int voteid;
	private boolean allowComment;
	private String copyfrom;

	@Id
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "content", nullable = false, length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "readpoint", nullable = false)
	public short getReadpoint() {
		return this.readpoint;
	}

	public void setReadpoint(short readpoint) {
		this.readpoint = readpoint;
	}

	@Column(name = "groupids_view", nullable = false, length = 100)
	public String getGroupidsView() {
		return this.groupidsView;
	}

	public void setGroupidsView(String groupidsView) {
		this.groupidsView = groupidsView;
	}

	@Column(name = "paginationtype", nullable = false)
	public boolean isPaginationtype() {
		return this.paginationtype;
	}

	public void setPaginationtype(boolean paginationtype) {
		this.paginationtype = paginationtype;
	}

	@Column(name = "maxcharperpage", nullable = false)
	public int getMaxcharperpage() {
		return this.maxcharperpage;
	}

	public void setMaxcharperpage(int maxcharperpage) {
		this.maxcharperpage = maxcharperpage;
	}

	@Column(name = "template", nullable = false, length = 30)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "paytype", nullable = false)
	public boolean isPaytype() {
		return this.paytype;
	}

	public void setPaytype(boolean paytype) {
		this.paytype = paytype;
	}

	@Column(name = "relation", nullable = false)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Column(name = "voteid", nullable = false)
	public int getVoteid() {
		return this.voteid;
	}

	public void setVoteid(int voteid) {
		this.voteid = voteid;
	}

	@Column(name = "allow_comment", nullable = false)
	public boolean isAllowComment() {
		return this.allowComment;
	}

	public void setAllowComment(boolean allowComment) {
		this.allowComment = allowComment;
	}

	@Column(name = "copyfrom", nullable = false, length = 100)
	public String getCopyfrom() {
		return this.copyfrom;
	}

	public void setCopyfrom(String copyfrom) {
		this.copyfrom = copyfrom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof V9NewsData))
			return false;
		V9NewsData castOther = (V9NewsData) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getContent() == castOther.getContent()) || (this
				.getContent() != null && castOther.getContent() != null && this
				.getContent().equals(castOther.getContent())))
				&& (this.getReadpoint() == castOther.getReadpoint())
				&& ((this.getGroupidsView() == castOther.getGroupidsView()) || (this
				.getGroupidsView() != null
				&& castOther.getGroupidsView() != null && this
				.getGroupidsView().equals(castOther.getGroupidsView())))
				&& (this.isPaginationtype() == castOther.isPaginationtype())
				&& (this.getMaxcharperpage() == castOther.getMaxcharperpage())
				&& ((this.getTemplate() == castOther.getTemplate()) || (this
				.getTemplate() != null
				&& castOther.getTemplate() != null && this
				.getTemplate().equals(castOther.getTemplate())))
				&& (this.isPaytype() == castOther.isPaytype())
				&& ((this.getRelation() == castOther.getRelation()) || (this
				.getRelation() != null
				&& castOther.getRelation() != null && this
				.getRelation().equals(castOther.getRelation())))
				&& (this.getVoteid() == castOther.getVoteid())
				&& (this.isAllowComment() == castOther.isAllowComment())
				&& ((this.getCopyfrom() == castOther.getCopyfrom()) || (this
				.getCopyfrom() != null
				&& castOther.getCopyfrom() != null && this
				.getCopyfrom().equals(castOther.getCopyfrom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getContent() == null ? 0 : this.getContent().hashCode());
		result = 37 * result + this.getReadpoint();
		result = 37
				* result
				+ (getGroupidsView() == null ? 0 : this.getGroupidsView()
				.hashCode());
		result = 37 * result + (this.isPaginationtype() ? 1 : 0);
		result = 37 * result + this.getMaxcharperpage();
		result = 37 * result
				+ (getTemplate() == null ? 0 : this.getTemplate().hashCode());
		result = 37 * result + (this.isPaytype() ? 1 : 0);
		result = 37 * result
				+ (getRelation() == null ? 0 : this.getRelation().hashCode());
		result = 37 * result + this.getVoteid();
		result = 37 * result + (this.isAllowComment() ? 1 : 0);
		result = 37 * result
				+ (getCopyfrom() == null ? 0 : this.getCopyfrom().hashCode());
		return result;
	}


}
