package com.xst.bean;
// Generated 2016-2-20 22:32:32 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * V9NewsData generated by hbm2java
 */
@Entity
@Table(name = "v9_news_data", catalog = "db_xst")
public class V9NewsData implements java.io.Serializable {

	private V9NewsDataId id;

	public V9NewsData() {
	}

	public V9NewsData(V9NewsDataId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "content", column = @Column(name = "content", nullable = false, length = 16777215)),
			@AttributeOverride(name = "readpoint", column = @Column(name = "readpoint", nullable = false)),
			@AttributeOverride(name = "groupidsView", column = @Column(name = "groupids_view", nullable = false, length = 100)),
			@AttributeOverride(name = "paginationtype", column = @Column(name = "paginationtype", nullable = false)),
			@AttributeOverride(name = "maxcharperpage", column = @Column(name = "maxcharperpage", nullable = false)),
			@AttributeOverride(name = "template", column = @Column(name = "template", nullable = false, length = 30)),
			@AttributeOverride(name = "paytype", column = @Column(name = "paytype", nullable = false)),
			@AttributeOverride(name = "relation", column = @Column(name = "relation", nullable = false)),
			@AttributeOverride(name = "voteid", column = @Column(name = "voteid", nullable = false)),
			@AttributeOverride(name = "allowComment", column = @Column(name = "allow_comment", nullable = false)),
			@AttributeOverride(name = "copyfrom", column = @Column(name = "copyfrom", nullable = false, length = 100)) })
	public V9NewsDataId getId() {
		return this.id;
	}

	public void setId(V9NewsDataId id) {
		this.id = id;
	}

}
